# Introduction to NumPy

This notebook contains my introductory NumPy notes and practice examples from my data science and machine learning studies.

## Learning objectives

- Understand why NumPy arrays are useful
- Create one-dimensional arrays
- Perform element-wise arithmetic
- Generate sequences and random values
- Select values using indexing and slicing

## 1. Setup

NumPy is conventionally imported with the alias `np`. Anaconda usually includes NumPy, so a separate installation is generally unnecessary.

In [1]:
import numpy as np

print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.5


## 2. From Python lists to NumPy arrays

A Python list is a general-purpose container. A NumPy array is designed for efficient numerical computation and supports vectorized operations.

In [2]:
my_list = [10, 20, 30, 40]
my_array = np.array(my_list)

print("List type:", type(my_list))
print("Array type:", type(my_array))
print("Array:", my_array)

List type: <class 'list'>
Array type: <class 'numpy.ndarray'>
Array: [10 20 30 40]


Useful array attributes:

- `ndim`: number of dimensions
- `shape`: size along each dimension
- `size`: total number of elements
- `dtype`: data type stored in the array

In [3]:
my_numpy_array = np.array([10, 20, 30, 40, 50])

print("Dimensions:", my_numpy_array.ndim)
print("Shape:", my_numpy_array.shape)
print("Size:", my_numpy_array.size)
print("Data type:", my_numpy_array.dtype)
print("Maximum value:", my_numpy_array.max())

Dimensions: 1
Shape: (5,)
Size: 5
Data type: int64
Maximum value: 50


## 3. Creating arrays

NumPy provides helper functions for creating arrays with predefined or random values.

In [4]:
ones_array = np.ones(5)
zeros_array = np.zeros(5)

print("Ones:", ones_array)
print("Zeros:", zeros_array)

Ones: [1. 1. 1. 1. 1.]
Zeros: [0. 0. 0. 0. 0.]


## 4. Array arithmetic

The `+` operator concatenates Python lists. With NumPy arrays, arithmetic operators work **element by element**.

In [5]:
list_1 = [1, 2]
list_2 = [2, 3]

array_1 = np.array(list_1)
array_2 = np.array(list_2)

print("List concatenation:", list_1 + list_2)
print("Array addition:", array_1 + array_2)
print("Array subtraction:", array_1 - array_2)
print("Array multiplication:", array_1 * array_2)
print("Array division:", array_1 / array_2)
print("Scalar multiplication:", array_1 * 5)

List concatenation: [1, 2, 2, 3]
Array addition: [3 5]
Array subtraction: [-1 -1]
Array multiplication: [2 6]
Array division: [0.5        0.66666667]
Scalar multiplication: [ 5 10]


> **Key idea:** Vectorized operations let us apply a calculation to an entire array without writing a Python loop.

## 5. Basic aggregation

Aggregation methods summarize all values in an array.

In [6]:
values = np.array([10, 20, 30, 40, 50])

print("Minimum:", values.min())
print("Maximum:", values.max())
print("Sum:", values.sum())
print("Mean:", values.mean())

Minimum: 10
Maximum: 50
Sum: 150
Mean: 30.0


## 6. Creating sequences with `arange`

`np.arange(start, stop, step)` works similarly to Python's `range`, but returns a NumPy array. The `stop` value is excluded.

In [7]:
python_sequence = list(range(0, 10))
numpy_sequence = np.arange(0, 10)
even_numbers = np.arange(0, 20, 2)

print("Python range as a list:", python_sequence)
print("NumPy sequence:", numpy_sequence)
print("Even numbers:", even_numbers)

Python range as a list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
NumPy sequence: [0 1 2 3 4 5 6 7 8 9]
Even numbers: [ 0  2  4  6  8 10 12 14 16 18]


## 7. Indexing and slicing

Indexing selects a single value, while slicing selects a range of values.

Slice syntax: `array[start:stop:step]`. The `stop` index is excluded, and negative indices count from the end.

In [8]:
numbers = np.arange(0, 10)

print("Original array:", numbers)
print("First element:", numbers[0])
print("Last element:", numbers[-1])
print("Elements from index 1 to 3:", numbers[1:4])
print("Every second element from index 2 to 5:", numbers[2:6:2])
print("Reversed array:", numbers[::-1])

Original array: [0 1 2 3 4 5 6 7 8 9]
First element: 0
Last element: 9
Elements from index 1 to 3: [1 2 3]
Every second element from index 2 to 5: [2 4]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


## 8. Random number generation

`default_rng` is NumPy's modern random-number interface. A fixed seed makes the results reproducible, which is useful for learning, debugging, and machine learning experiments.

In [9]:
rng = np.random.default_rng(seed=42)

uniform_values = rng.random(5)
normal_values = rng.standard_normal(4)
random_matrix = rng.standard_normal((4, 4))
random_integers = rng.integers(1, 300, size=5)

print("Uniform values between 0 and 1:", uniform_values)
print("Normally distributed values:", normal_values)
print("Random 4×4 matrix:\n", random_matrix)
print("Random integers:", random_integers)

Uniform values between 0 and 1: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Normally distributed values: [-1.30217951  0.1278404  -0.31624259 -0.01680116]
Random 4×4 matrix:
 [[-0.85304393  0.87939797  0.77779194  0.0660307 ]
 [ 1.12724121  0.46750934 -0.85929246  0.36875078]
 [-0.9588826   0.8784503  -0.04992591 -0.18486236]
 [-0.68092954  1.22254134 -0.15452948 -0.42832782]]
Random integers: [228  59 109 140 149]


## Summary

In this notebook, I learned how to:

- Convert Python lists into NumPy arrays
- Inspect array properties
- Create arrays filled with zeros, ones, sequences, or random values
- Perform vectorized arithmetic and basic aggregations
- Access array elements with indexing and slicing

### Further reading

- [A Visual Intro to NumPy](https://jalammar.github.io/visual-numpy/)
- [NumPy documentation](https://numpy.org/doc/stable/)